### ISSUE TITLE
Frozen sketch + Breaks on reload

### ISSUE THREAD

**Issue by jchwenger** [colormotor/py5canvas#5]
Hi Daniel,

Weird situation: I just tried to do a fresh install of canvas through conda (and pip), and I can run the basic animation without a problem, except it does not go beyond the first frame (I can print `framecount`, it stays at zero).

What is more, if I change the source file, the script fails [here](https://github.com/colormotor/py5canvas/blob/30090a31130108ada358af1282bb9ddcd7d708e7/py5canvas/run_sketch.py#L110), with:
```
Traceback (most recent call last):
  File "/Users/jcw/Documents/teaching/DMLCP/DMLCP/canvas/basic_animation.py", line 20, in <module>
  File "/Users/jcw/Documents/teaching/DMLCP/DMLCP/canvas/env/lib/python3.10/site-packages/py5canvas/__init__.py", line 62, in run
    run_sketch.main(filename, fps=frame_rate, inject=inject, show_toolbar=show_toolbar)
  File "/Users/jcw/Documents/teaching/DMLCP/DMLCP/canvas/env/lib/python3.10/site-packages/py5canvas/run_sketch.py", line 1315, in main
    sketch.check_reload()
  File "/Users/jcw/Documents/teaching/DMLCP/DMLCP/canvas/env/lib/python3.10/site-packages/py5canvas/run_sketch.py", line 801, in check_reload
    if self.must_reload or self.watcher.modified(): # Every frame check for file modification
  File "/Users/jcw/Documents/teaching/DMLCP/DMLCP/canvas/env/lib/python3.10/site-packages/py5canvas/run_sketch.py", line 110, in modified
    stamp = os.stat(self.filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/Users/jcw/Documents/teaching/DMLCP/DMLCP/canvas/basic_animation.py'
```

And that's even as the file exists (I'm running it)...

This modification solves it, but it's a bit strange, as the file does exist...
```python
    def modified(self):
        if os.path.isfile(self.filename): # check for existence
            stamp = os.stat(self.filename).st_mtime
            if self._cached_stamp is None:
                self._cached_stamp = stamp
            if stamp != self._cached_stamp:
                self._cached_stamp = stamp
                return True
        return False
```

Any thougts? Thanks!

**Comment by colormotor** [comment]
Hi Jeremie,
I tried to reproduce on my machine but it seems to work.
What platform are you running this on? 
Also, did you run the sketch from the command line, from visual studio code or otherwise?

**Comment by jchwenger** [comment]
Strange, strange. It's on Sonoma 14.4, on a MacBook Air M2, run directly from the terminal: `python basic_animation.py`...

**Comment by jchwenger** [comment]
I tried it using both the `conda` install pulling your `.yaml` file, and creating a `venv` with python3.10.13 and installing everything through pip using a `requirements.canvas.txt` file containing this:
```
# requires python3.10!
jupyter
numpy
pycairo
matplotlib
opencv-python
pyglfw
moderngl
py5canvas
```

However, the situation is the same in both cases, and I can't quite pinpoint why (I had done another fresh install earlier this summer and the loop certainly worked without an issue).

**Comment by jchwenger** [comment]
Come to think of it, I note the following errors when run the script:
```
[Errno 2] No such file or directory: '/Users/jcw/Documents/teaching/DMLCP/DMLCP/canvas/osc.json'
Unable to load json file:/Users/jcw/Documents/teaching/DMLCP/DMLCP/canvas/osc.json
Starting OSC Server
Initializing OSC client
[Errno 2] No such file or directory: '/Users/jcw/Documents/teaching/DMLCP/DMLCP/canvas/env/lib/python3.10/site-packages/py5canvas/settings.json'
Unable to load json file:/Users/jcw/Documents/teaching/DMLCP/DMLCP/canvas/env/lib/python3.10/site-packages/py5canvas/settings.json
```

Wondering if that `settings.json` is what's causing the issue?

[Edit: Ignore this bit, saw the mention in the docs!] Also, makes me notice that `python-osc` might be missing from the `.yaml` file?

**Comment by colormotor** [comment]
Oh wait there was a bug with "settings" but the latest version should fix it, have you tried to
```
pip install --upgrade py5canvas
```
(or pull if you work with a local version of the repo)
?

**Comment by jchwenger** [comment]
Sadly, I just tried, but the error remains.

Earlier I had done `pip install git+https://github.com/colormotor/py5canvas.git`, so it should have been the latest version...

**Comment by colormotor** [comment]
Looking back at the error you initially got this is a bit weird, since the path `/Users/jcw/Documents/teaching/DMLCP/DMLCP/canvas/basic_animation.py` is absolute so I would assume it exists. Can you double check that that path is correct?

**Comment by jchwenger** [comment]
I can't see anything wrong there, that's the path to the file I'm executing in my local directory... (Unless there's some non-printable character in there...) Also, the strangest thing is that indeed if I add a guard as shown above, `if os.path.isfile(self.filename)`, then this bit runs smoothly (reloading with modifications), but not the loop.

Perhaps something to note: when I change the sketch, I get the error about the file not existing, but the script does not stop running entirely: I still have to do Ctrl+C once more, and when I do there's this as well:

```
^CException ignored in: <module 'threading' from '/Users/jcw/.pyenv/versions/3.10.13/lib/python3.10/threading.py'>
Traceback (most recent call last):
  File "/Users/jcw/.pyenv/versions/3.10.13/lib/python3.10/threading.py", line 1567, in _shutdown
    lock.acquire()
KeyboardInterrupt: 
```

The loop hanging forever could actually look like a locked thread??

**Comment by colormotor** [comment]
Solved with a workaround (283fdd0). Need to improve file modified polling (#6)
